#!/usr/bin/env python3
"""Generate the embedded Outfit subsets and monochrome Bits & Bytes icons.

This is a developer-only tool. The generated headers are committed, so neither
Python nor these packages are required by desktop or STM32 builds.
"""

from __future__ import annotations

import argparse
import io
from pathlib import Path

import cairosvg
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image


FONT_CODEPOINTS = (
    set(range(0x20, 0x180))  # Basic Latin, Latin-1 and Latin Extended-A.
    | {0x20AC}               # Euro sign.
)

CUSTOM_SVGS = {
    "back": """<svg width="20" height="20" viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"><path d="M12.75 3.5 L6.25 10 L12.75 16.5"
        fill="none" stroke="#000" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round"/></svg>""",
    "check": """<svg width="20" height="20" viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"><path d="M3.5 10.5 L8 15 L16.5 5.5"
        fill="none" stroke="#000" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round"/></svg>""",
}

ICONS = (
    ("settings", "icon-settings.svg"),
    ("delete", "icon-delete.svg"),
    ("close", "icon-close.svg"),
    ("signature", "icon-signature.svg"),
    ("back", None),
    ("check", None),
)


def c_array(name: str, data: bytes, columns: int = 12) -> str:
    lines = []
    for offset in range(0, len(data), columns):
        values = ", ".join(f"0x{value:02x}" for value in data[offset:offset + columns])
        lines.append(f"    {values},")
    return f"static const unsigned char {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def subset_font(source: Path, weight: int, output: Path) -> bytes:
    font = TTFont(str(source))
    instantiateVariableFont(font, {"wght": weight}, inplace=True, optimize=True)

    options = subset.Options()
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.name_languages = [0x409]
    options.name_legacy = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.layout_features = ["kern"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=FONT_CODEPOINTS)
    subsetter.subset(font)
    font.save(str(output))
    return output.read_bytes()


def raster_icon(svg: bytes, size: int = 20, oversample: int = 4) -> bytes:
    png = cairosvg.svg2png(
        bytestring=svg,
        output_width=size * oversample,
        output_height=size * oversample,
    )
    image = Image.open(io.BytesIO(png)).convert("RGBA")
    image = image.resize((size, size), Image.Resampling.LANCZOS)
    return image.getchannel("A").tobytes()


def write_font_header(output: Path, regular: bytes, semibold: bytes) -> None:
    content = """// Generated by tools/generate_branded_assets.py. Do not edit manually.
#ifndef BITS_BYTES_OUTFIT_FONTS_H
#define BITS_BYTES_OUTFIT_FONTS_H

"""
    content += c_array("kOutfitRegularSubset", regular)
    content += f"static const unsigned int kOutfitRegularSubsetSize = {len(regular)}u;\n\n"
    content += c_array("kOutfitSemiBoldSubset", semibold)
    content += f"static const unsigned int kOutfitSemiBoldSubsetSize = {len(semibold)}u;\n\n"
    content += "#endif\n"
    output.write_text(content, encoding="utf-8", newline="\n")


def write_icon_header(output: Path, frontend: Path) -> None:
    icon_dir = frontend / "src" / "assets" / "ui"
    content = """// Generated from the management-platform icon set by
// tools/generate_branded_assets.py. Monochrome alpha masks are packed into the
// ImGui font atlas at startup; no SVG parser is used on the target.
#ifndef BITS_BYTES_BRANDED_ICONS_H
#define BITS_BYTES_BRANDED_ICONS_H

static const int kBrandedIconSize = 20;

"""
    for name, filename in ICONS:
        if filename is None:
            svg = CUSTOM_SVGS[name].encode("utf-8")
        else:
            svg = (icon_dir / filename).read_bytes()
        camel = "".join(part.capitalize() for part in name.split("_"))
        content += c_array(f"kIcon{camel}Alpha", raster_icon(svg)) + "\n"
    content += "#endif\n"
    output.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--frontend", type=Path, required=True,
                        help="Path to the management platform frontend directory")
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1],
                        help="IMGUI project root (defaults to this repository)")
    args = parser.parse_args()

    project = args.output.resolve()
    frontend = args.frontend.resolve()
    source_font = frontend / "src" / "assets" / "fonts" / "Outfit-Variable.ttf"
    if not source_font.is_file():
        raise SystemExit(f"Outfit source font not found: {source_font}")

    font_dir = project / "assets" / "fonts"
    icon_dir = project / "assets" / "ui"
    font_dir.mkdir(parents=True, exist_ok=True)
    icon_dir.mkdir(parents=True, exist_ok=True)

    regular_path = font_dir / "Outfit-Regular-Subset.ttf"
    semibold_path = font_dir / "Outfit-SemiBold-Subset.ttf"
    regular = subset_font(source_font, 400, regular_path)
    semibold = subset_font(source_font, 600, semibold_path)
    write_font_header(font_dir / "outfit_fonts.h", regular, semibold)
    write_icon_header(icon_dir / "branded_icons.h", frontend)

    print(f"Outfit regular subset:  {len(regular)} bytes")
    print(f"Outfit semibold subset: {len(semibold)} bytes")
    print("Generated six 20x20 monochrome icon masks")


if __name__ == "__main__":
    main()
